[tool.poetry]
name = "data-catalogue-ingestion"
version = "0.1.0"
description = "Ingestion environment for data catalogue data sources"
authors = ["Murdo Moyse <murdo.moyse@digital.justice.gov.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.3"
boto3 = "^1.34.119"
datahub = "^0.999.1"
moto = "4"
pandas = "^2.2.2"
acryl-datahub = { extras = ["dbt"], version = "==0.14.1" }
semantic-version = "^2.10.0"
botocore = "^1.34.162"

[tool.poetry.group.dev.dependencies]
vcrpy = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
