{
 "title": "DataHub Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Get QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_get_Count{}[1m])/60",
     "legendFormat": "Get QPS"
    }
   ]
  },
  {
   "title": "Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_Mean",
     "legendFormat": "Get Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_75thPercentile",
     "legendFormat": "Get P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_95thPercentile",
     "legendFormat": "Get P95"
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingest QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_Count{}[1m])/60",
     "legendFormat": "Ingest Count"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchIngest_Count{}[1m])/60",
     "legendFormat": "BatchIngest Count"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_Count{}[1m])/60 - increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_success_Count{}[1m])/60",
     "legendFormat": "Ingest Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_success_Count{}[1m])/60",
     "legendFormat": "BatchIngest Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_success_Count{}[1m])/60",
     "legendFormat": "Ingest Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchIngest_Count{}[1m])/60 - increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_success_Count{}[1m])/60",
     "legendFormat": "BatchIngest Failure"
    }
   ]
  },
  {
   "title": "Ingest Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Ingest Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_entity_EntityServiceImpl_ingestAspectsToLocalDB_Mean",
     "legendFormat": "Ingest To DB"
    }
   ]
  },
  {
   "title": "MCL Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_consume_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_consume_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_consume_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "EventGenerator Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Ingestion Scheduler latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_Mean",
     "legendFormat": "Average"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Entity Change Event Generator Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_EntityChangeEventGeneratorHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Ingestion Scheduler latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_IngestionSchedulerHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Sibling Association latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 26 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_SiblingAssociationHook_latency_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_SiblingAssociationHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_SiblingAssociationHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Update Indices latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_UpdateIndicesHook_latency_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_UpdateIndicesHook_latency_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_UpdateIndicesHook_latency_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Search QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Count{}[1m])/60",
     "legendFormat": "QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_success_Count{}[1m])/60",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Search Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 43 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESSearchDAO_aggregateByValue_search_Mean",
     "legendFormat": "Aggregate by value Search"
    },
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESSearchDAO_searchRequest_Mean",
     "legendFormat": "Request Builder"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Mean",
     "legendFormat": "Total Search"
    }
   ]
  },
  {
   "title": "Browse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Browse QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Count{}[1m])/60",
     "legendFormat": "QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_success_Count{}[1m])/60",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Browse Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 52 },
   "targets": [
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browseV2_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browseV2_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browseV2_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Browse Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 52 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESBrowseDAO_esGroupSearch_Mean",
     "legendFormat": "ES Groups Query"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browseV2_Mean",
     "legendFormat": "Total Browse"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graph QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "increase(metrics_com_datahub_graphql_GraphQLController_searchAcrossLineage_Count{}[1m])/60",
     "legendFormat": "Search across Lineage QPS"
    }
   ]
  },
  {
   "title": "Graph Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 61 },
   "targets": [
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_searchAcrossLineage_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_searchAcrossLineage_75thPercentile",
     "legendFormat": "Search across Lineage P75"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_searchAcrossLineage_95thPercentile",
     "legendFormat": "Search across Lineage P95"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Producer Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_producer_producer_topic_metrics_record_send_rate{})"
    }
   ]
  },
  {
   "title": "Consumer Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum by (client_id) (kafka_consumer_consumer_metrics_request_rate{})"
    }
   ]
  },
  {
   "title": "MetadataChangeEvent Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "MetadataChangeProposal Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "MetadataChangeLog Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "DataHubUsageEvent Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}