{
 "title": "DataHub deployment status dashboard",
 "description": "High level application HTTP request and resource usage information.",
 "tags": [
  "kubernetes",
  "nginx-ingress"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{}, exported_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}, exported_service)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "domainName",
    "label": "DomainName",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, DomainName)\t"
   },
   {
    "name": "clientId",
    "label": "ClientId",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, ClientId)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{namespace='$namespace',container!=\"POD\",container!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by (container)(increase(container_cpu_usage_seconds_total{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m]))",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  { "title": "OpenSearch Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OS Cluster Status",
   "type": "timeseries",
   "description": "Indicates shard allocation status.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "Green",
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "Yellow",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "Yellow",
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "Red",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "Red",
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "OS master instance connection status",
   "type": "timeseries",
   "description": "Indicates where data nodes can reach the master node. Failures are usually the result of a network connectivity problem.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "expression": "m3",
     "label": "Green",
     "metricEditorMode": 1,
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Red",
     "expression": "(m3*(-2))+2",
     "label": "Red",
     "metricEditorMode": 1,
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "OS HTTP requests by response code",
   "type": "timeseries",
   "description": "The number of requests to a domain, aggregated by HTTP response code (2xx, 3xx, 4xx, 5xx).",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "2XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "2XX",
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "period": "1m",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "3XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "3XX",
     "metricName": "3xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "4XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "4XX",
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "5XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "5XX",
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Pod status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pod Replicas",
   "type": "timeseries",
   "description": "The number of pod replicas for the service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"pod\", \"$1\", \"created_by_name\", \"(.*)-\\\\w+\")\n) by (pod)",
     "legendFormat": "{{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "description": "This chart shows the count of pod/container restart events observed.  This will show \"CrashLooping\" error events.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[10m])) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Non-Ready Pods",
   "type": "timeseries",
   "description": "This chart shows the count of pods in an \"non-ready\" state.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Pending|Unknown\"}\n) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Resource usage (in-depth)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requested CPU Usage",
   "type": "timeseries",
   "description": "CPU usage in relation to the requested cpu for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage",
   "type": "timeseries",
   "description": "Average recorded CPU usage for each type container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Requested Memory Usage",
   "type": "timeseries",
   "description": "Memory usage in relation to the requested memory for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (container)\n* 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual Memory Usage",
   "type": "timeseries",
   "description": "Average recorded memory usage for a single type of container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  irate(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Frontend Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of HTTP requests by status",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__interval])\n) by (status) != 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Served",
   "type": "stat",
   "description": "The total number of requests served in the selected time period.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Mean Response Time (p100)",
   "type": "stat",
   "description": "The mean response time (p100 - all requests) over the selected timeframe.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p95)",
   "type": "stat",
   "description": "The mean response time (p95 - the 95th percentile of requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p50)",
   "type": "stat",
   "description": "The mean response time (p50 - the 50th percentile requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Frontend request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      exported_namespace =~ \"$namespace\",\n      ingress=~\"$service|$service-.+\",\n    }[1m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Recorded request duration from the ingress controllers in percentiles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "The percentage of HTTP responses that are non-error codes vs error codes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status!~\"5.*|499\"}[$__rate_interval]))\n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The percentage of all HTTP requests that result in a 5xx status.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"500\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "500"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"501\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "501"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"502\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "502"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"503\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "503"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"504\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "description": "This chart shows the number of blocked requests at the ingress level.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"429\"}[$__rate_interval])\n)\nor\nvector(0)",
     "legendFormat": "Rate Limited Reqs"
    },
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service|$service-.+\", exported_namespace=\"$namespace\", status=\"406\"}[$__rate_interval])\n)\nor\nvector(0)",
     "legendFormat": "Mod Security Blocked Reqs"
    }
   ]
  },
  {
   "title": "Network operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend Network I/O",
   "type": "timeseries",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\"}[2m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\"}[2m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-sum by (pod)(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\"}[2m]))",
     "legendFormat": "Receive datahub-frontend"
    },
    {
     "expr": "-sum by (pod)(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\".+gms-.+\"}[2m]))",
     "legendFormat": "Receive datahub-gms"
    },
    {
     "expr": "-sum by (pod)(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"opensearch-proxy-.+\"}[2m]))",
     "legendFormat": "Receive opensearch-proxy"
    },
    {
     "expr": "sum by (pod)(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\"}[2m]))",
     "legendFormat": "Transmit datahub-frontend"
    },
    {
     "expr": "sum by (pod)(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\".+-gms-.+\"}[2m]))",
     "legendFormat": "Transmit datahub-gms"
    },
    {
     "expr": "sum by (pod)(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"opensearch-proxy.+\"}[2m]))",
     "legendFormat": "Transmit opensearch-proxy"
    }
   ]
  }
 ]
}