apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datahub-service
  namespace: ${KUBE_NAMESPACE}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: datahub
  endpoints:
    - port: jmx
      interval: 15s
      relabelings:
        - separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
