datahub-gms:
  extraEnvs:
    # Override elasticsearch.bulkProcessor.requestsLimit
    # (default: 500)
    - name: ES_BULK_REQUESTS_LIMIT
      value: "1000"
    - name: ES_BULK_FLUSH_PERIOD
      value: "60"
