datahub-gms:
  extraEnvs:
    # Override elasticsearch.bulkProcessor.requestsLimit
    # (default: 500)
    - name: ES_BULK_REQUESTS_LIMIT
      value: "1000"
    - name: ES_BULK_FLUSH_PERIOD
      value: "60"

datahubUpgrade:
  restoreIndices:
    # See https://docs.datahub.com/docs/how/restore-indices/#kubernetes for more parameters
    args:
      - "-a"
      - "clean"
