datahub-gms:
  extraEnvs:
    # Override elasticsearch.bulkProcessor.requestsLimit
    # (default: 500)
    - name: ES_BULK_REQUESTS_LIMIT
      value: "250"
    - name: ES_BULK_FLUSH_PERIOD
      value: "15"

global:
  datahub_analytics_enabled: false
  elasticsearch:
    metadataChangeLog:
      hooks:
        ingestionScheduler:
          enabled: false
    index:
      settingsOverrides: '{"graph_service_v1":{"number_of_shards":"1"},"system_metadata_service_v1":{"number_of_shards":"1"}}'
      entitySettingsOverrides: '{"dataset":{"number_of_shards":"1"},"usage_event":{"number_of_shards":"1","number_of_replicas":"0"}}'
  kafka:
    metadataChangeLog:
      hooks:
        ingestionScheduler:
          enabled: false
