apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ${KUBE_NAMESPACE}-alerting-resource
  labels:
    role: alert-rules
    prometheus: cloud-platform
spec:
  groups:
    - name: application-rules
      rules:
        - alert: GMSCpuUsageHigh
          annotations:
            message: :warning:Service '{{"{{" }} $labels.container {{"}}"}}' cpu usage above threshold of 60%.
          expr: >-
            (sum(rate(container_cpu_usage_seconds_total{namespace="data-platform-datahub-catalogue-dev", container=~".+gms"}[5m])) 
            / sum(kube_pod_container_resource_limits{namespace="data-platform-datahub-catalogue-dev", container=~".+gms", unit="core"})) * 100  
            > 90
          for: 1m
          labels:
            severity: DataHub-${ENV}
        - alert: GMSMemUsageHigh
          annotations:
            message: :warning:Service '{{"{{" }} $labels.container {{"}}"}}' memory usage above 80%.
          expr: >-
            ((( sum(container_memory_working_set_bytes{container=~".+gms.+", namespace="${KUBE_NAMESPACE}"}) by (namespace,container,pod)  
            / sum(kube_pod_container_resource_limits{container=~".+gms.+",namespace="${KUBE_NAMESPACE}",unit="byte"}) by (namespace,container,pod) ) * 100 ) < +Inf )
             > 80
          for: 1m
          labels:
            severity: DataHub-${ENV}
        - alert: HighPersistantVolumeUsage
          annotations:
            message: :warning:Service '{{"{{" }} $labels.container {{"}}"}}' Persistent volume is using more than 90%
          expr: >-
            ((((sum(kubelet_volume_stats_used_bytes{namespace="${KUBE_NAMESPACE}"}) by (namespace,persistentvolumeclaim)) 
            / (sum(kubelet_volume_stats_capacity_bytes{namespace="${KUBE_NAMESPACE}"}) by (namespace,persistentvolumeclaim)))*100) < +Inf ) 
            > 90
          for: 5m
          labels:
            severity: DataHub-${ENV}
        - alert: KubeQuotaExceeded
          annotations:
            message:
              Namespace {{ $labels.namespace }} is using {{ printf "%0.0f" $value
              }}% of its {{ $labels.resource }} quota.
            runbook_url: https://runbooks.data-catalogue.service.justice.gov.uk/
            dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/2yTpJtUU4G8iGuqPdEkG/datahub-deployment-status-dashboard
          expr: |-
            100 * kube_resourcequota{namespace=~"${KUBE_NAMESPACE}", job="kube-state-metrics", type="used"}
              / ignoring(instance, job, type)
            (kube_resourcequota{namespace=~"${KUBE_NAMESPACE}", job="kube-state-metrics", type="hard"} > 0)
              > 90
          for: 15m
          labels:
            severity: DataHub-${ENV}
