name: Deploy staged

on:
  push:
    paths:
      - 'helm_deploy/**'
      - '.github/workflows/**deploy**'
      - '!helm_deploy/**test**'
      - '!.github/workflows/**test**'
    branches: 
      - 'main'

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      env: test
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      postgres_host: ${{ secrets.POSTGRES_HOST}}
      postgres_client_host: ${{ secrets.POSTGRES_CLIENT_HOST }} 
      postgres_url: ${{ secrets.POSTGRES_URL }}
      opensearch_proxy_host: ${{ secrets.OPENSEARCH_PROXY_HOST }}

  deploy-preprod:
    uses: ./.github/workflows/deploy-workflow.yml
    needs: [deploy-test]
    with:
      env: preprod
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      postgres_host: ${{ secrets.POSTGRES_HOST}}
      postgres_client_host: ${{ secrets.POSTGRES_CLIENT_HOST }} 
      postgres_url: ${{ secrets.POSTGRES_URL }}
      opensearch_proxy_host: ${{ secrets.OPENSEARCH_PROXY_HOST }}
