name: Deploy dev

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      env: dev
      datahub_helm_version: "0.3.30"
      datahub_prereqs_helm_version: "0.1.8"
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      postgres_host: ${{ secrets.POSTGRES_HOST}}
      postgres_client_host: ${{ secrets.POSTGRES_CLIENT_HOST }} 
      postgres_url: ${{ secrets.POSTGRES_URL }}
      opensearch_proxy_host: ${{ secrets.OPENSEARCH_PROXY_HOST }}
