name: Deploy dev

on:
  pull_request:
    paths:
      - 'helm_deploy/**'
      - '.github/workflows/**deploy**'
      - '!helm_deploy/**test**'
      - '!.github/workflows/**test**'
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      env: dev
      datahub_helm_version: "0.6.7"
      datahub_prereqs_helm_version: "0.1.15"
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      postgres_host: ${{ secrets.POSTGRES_HOST}}
      postgres_client_host: ${{ secrets.POSTGRES_CLIENT_HOST }}
      postgres_url: ${{ secrets.POSTGRES_URL }}
      postgres_username: ${{ secrets.POSTGRES_USERNAME }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
      postgres_db_name: ${{ secrets.POSTGRES_DB_NAME }}
      opensearch_proxy_host: ${{ secrets.OPENSEARCH_PROXY_HOST }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      limit_whitelist: ${{ secrets.LIMIT_WHITELIST }}
