name: Ingest metadata to test
on:
  # schedule:
  #   - cron: "0 3 * * *" # 3am UTC
  workflow_dispatch:

jobs:
  ingest-ownership-types-test:
    uses: ./.github/workflows/ingest-ownership-types.yml
    with:
      ENVIRONMENT: test-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-cadet-test:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: test
      CADET_INGESTION_RECIPE_PATH: ingestion/cadet.yaml
      S3_TARGET_LOCATION: s3://mojap-derived-tables/prod/run_artefacts/deploy-docs/latest/target
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-em-cadet-test:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: test
      CADET_INGESTION_RECIPE_PATH: ingestion/cadet_electronic_monitoring.yaml
      S3_TARGET_LOCATION: s3://emds-prod-cadt/em_data_artefacts/prod/run_artefacts/emds-deploy-docs/latest/target
      BASE_CADET_INGESTION: false
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.EM_CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-justice-data-test:
    uses: ./.github/workflows/ingest-justice-data.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-glue-data-test:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      SOP_TECHNICAL_CONTACT: ${{ secrets.SOP_TECHNICAL_CONTACT }}
      CONTRACTS_TECHNICAL_CONTACT: ${{ secrets.CONTRACTS_TECHNICAL_CONTACT }}
      COURTS_CRIMINAL_TECHNICAL_CONTACT: ${{ secrets.COURTS_CRIMINAL_TECHNICAL_CONTACT }}
      COURTS_FAMILY_TECHNICAL_CONTACT: ${{ secrets.COURTS_FAMILY_TECHNICAL_CONTACT }}
      JUST_LINK_TECHNICAL_CONTACT: ${{ secrets.JUST_LINK_TECHNICAL_CONTACT }}
  ingest-moj-publications-test:
    uses: ./.github/workflows/ingest-moj-publications.yml
    with:
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
