name: "Ingest DBT metadata from Create a Derived Table"

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ECR_REGION:
        description: "ecr region to connect to"
        required: false
        type: string
        default: eu-west-1
      ENVIRONMENT:
        description: "Environment to use for secrets"
        required: true
        type: string
    secrets:
      DATAHUB_GMS_TOKEN:
        description: "API Key for datahub GMS"
        required: true
      CADET_METADATA_ROLE_TO_ASSUME:
        description: "AWS role to assume, which can access CaDeT metadata in S3"
        required: true
      SLACK_ALERT_WEBHOOK:
        description: "Webhook for posting alerts to the team"
        required: true

jobs:
  datahub-ingest:
    environment: ${{ inputs.ENVIRONMENT }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - run: echo "ENVIRONMENT=${{inputs.ENVIRONMENT}}; URL=${{vars.DATAHUB_GMS_URL}}"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.ECR_REGION }}
      - name: install reqs
        run: pip install acryl-datahub[dbt]
      - name: push metadata to datahub
        env:
          DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
          DATAHUB_GMS_URL: ${{ vars.DATAHUB_GMS_URL }}
          DATAHUB_TELEMETRY_ENABLED: false
        run: datahub ingest -c ingestion/cadet.yaml

      - name: Notify on failure
        uses: slackapi/slack-github-action@v1.26.0
        if: job.status == 'failure'
        with:
          channel-id: "C071VNHPUHZ"
          payload: |
            {
                "text": ":warning: Unable to ingest CaDeT metadata on ${{inputs.env}}!",
                "blocks": [
                {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action run result: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                }
                ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ALERT_WEBHOOK }}
