name: Ingest metadata to prod
on:
  schedule:
    - cron: "15 7 * * *" # 7:15am UTC
  workflow_dispatch:

jobs:
  ingest-ownership-types-prod:
    uses: ./.github/workflows/ingest-yaml.yml
    with:
      ENVIRONMENT: prod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-cadet-prod:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: prod-ingestion
      CADET_INGESTION_RECIPE_PATH: ingestion/cadet.yaml
      S3_TARGET_LOCATION: s3://mojap-derived-tables/prod/run_artefacts/deploy-docs/latest/target
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-em-cadet-prod:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: prod-ingestion
      CADET_INGESTION_RECIPE_PATH: ingestion/cadet_electronic_monitoring.yaml
      S3_TARGET_LOCATION: s3://emds-prod-cadt/em_data_artefacts/prod/run_artefacts/emds-deploy-docs/latest/target
      BASE_CADET_INGESTION: false
      CADET_INSTANCE: cadet_electronic_monitoring.awsdatacatalog
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.EM_CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-justice-data-prod:
    uses: ./.github/workflows/ingest-justice-data.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: prod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-glue-data-prod:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ENVIRONMENT: prod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      SOP_TECHNICAL_CONTACT: ${{ secrets.SOP_TECHNICAL_CONTACT }}
      CONTRACTS_TECHNICAL_CONTACT: ${{ secrets.CONTRACTS_TECHNICAL_CONTACT }}
      COURTS_CRIMINAL_TECHNICAL_CONTACT: ${{ secrets.COURTS_CRIMINAL_TECHNICAL_CONTACT }}
      COURTS_FAMILY_TECHNICAL_CONTACT: ${{ secrets.COURTS_FAMILY_TECHNICAL_CONTACT }}
      JUST_LINK_TECHNICAL_CONTACT: ${{ secrets.JUST_LINK_TECHNICAL_CONTACT }}
      FINES_TECHNICAL_CONTACT: ${{ secrets.FINES_TECHNICAL_CONTACT }}
      PLACEHOLDER_TECHNICAL_CONTACT: ${{ secrets.PLACEHOLDER_TECHNICAL_CONTACT }}
  ingest-moj-publications-prod:
    uses: ./.github/workflows/ingest-moj-publications.yml
    with:
      ENVIRONMENT: prod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-postgres-cdrs:
    uses: ./.github/workflows/ingest-postgres.yml
    with:
      ENVIRONMENT: prod-ingestion
      INGESTION_NAME: hmpps_calculate_release_dates
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      HOST_PORT: ${{ secrets.POSTGRES_HOST_PORT_CALCULATE_RELEASE_DATES_PREPROD }}
      DATABASE: ${{ secrets.POSTGRES_DATABASE_CALCULATE_RELEASE_DATES_PREPROD }}
      USER: ${{ secrets.POSTGRES_USER_CALCULATE_RELEASE_DATES_PREPROD }}
      PASSWORD: ${{ secrets.POSTGRES_PASSWORD_CALCULATE_RELEASE_DATES_PREPROD }}
      PLACEHOLDER_TECHNICAL_CONTACT: ${{ secrets.PLACEHOLDER_TECHNICAL_CONTACT }}

