name: "Ingest metadata from Justice Data public api"

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ECR_REGION:
        description: "ecr region to connect to"
        required: false
        type: string
        default: eu-west-1
      ENVIRONMENT:
        description: "Environment to use for secrets"
        required: true
        type: string
    secrets:
      DATAHUB_GMS_TOKEN:
        description: "API Key for datahub GMS"
        required: true
      SLACK_ALERT_WEBHOOK:
        description: "Webhook for posting alerts to the team"
        required: true

jobs:
  datahub-ingest-justice-data:
    environment: ${{ inputs.ENVIRONMENT }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install UV
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.17"
      
      - name: Install Project Dependencies
        run: uv sync --locked

      - name: justice data datahub ingestion
        env:
          DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
          DATAHUB_GMS_URL: ${{ vars.DATAHUB_GMS_URL }}
          DATAHUB_TELEMETRY_ENABLED: false
        run: time uv run datahub ingest -c ingestion/justice_data_ingest.yaml

      - name: Notify on failure
        uses: slackapi/slack-github-action@v2.1.0
        if: job.status == 'failure'
        with:
          webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":warning: Justice Data ingestion failure on ${{inputs.ENVIRONMENT}} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
