name: Ingest metadata to preprod on schedule

on:
  schedule:
    - cron: "0 9 * * *" # 9am UTC
  workflow_dispatch:

jobs:
  ingest-ownership-types-preprod:
    uses: ./.github/workflows/ingest-ownership-types.yml
    with:
      ENVIRONMENT: preprod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-cadet-preprod:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: preprod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-justice-data-preprod:
    uses: ./.github/workflows/ingest-justice-data.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: preprod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-glue-data-preprod:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ENVIRONMENT: preprod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-moj-publications-preprod:
    uses: ./.github/workflows/ingest-moj-publications.yml
    with:
      ENVIRONMENT: preprod-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
