name: Ingest metadata to test
on:
  # schedule:
  #   - cron: "0 3 * * *" # 3am UTC
  workflow_dispatch:

jobs:
  ingest-ownership-types-test:
    uses: ./.github/workflows/ingest-ownership-types.yml
    with:
      ENVIRONMENT: test-ingestion
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-cadet-test:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-justice-data-test:
    uses: ./.github/workflows/ingest-justice-data.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-glue-data-test:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ENVIRONMENT: test
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
