name: "Ingest metadata from yaml"

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Environment to use for secrets"
        required: true
        type: string
    secrets:
      DATAHUB_GMS_TOKEN:
        description: "API Key for datahub GMS"
        required: true
      SLACK_ALERT_WEBHOOK:
        description: "Webhook for posting alerts to the team"
        required: true

jobs:
  datahub-ingest-ownership-types:
    environment: ${{ inputs.ENVIRONMENT }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - run: echo "ENVIRONMENT=${{inputs.ENVIRONMENT}}; URL=${{vars.DATAHUB_GMS_URL}}"
      - uses: actions/checkout@v4
      
      - name: Install UV
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.17"
          python-version: ${{ vars.PYTHON_VERSION }}
      
      - name: Install Project Dependencies
        run: uv sync --locked

      - name: ownership types ingestion
        env:
          DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
          DATAHUB_GMS_URL: ${{ vars.DATAHUB_GMS_URL }}
          DATAHUB_TELEMETRY_ENABLED: false
        run: time uv run datahub ingest -c ingestion/create_custom_ownership_types.yaml

      - name: tags ingestion
        env:
          DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
          DATAHUB_GMS_URL: ${{ vars.DATAHUB_GMS_URL }}
          DATAHUB_TELEMETRY_ENABLED: false
        run: time uv run datahub ingest -c ingestion/ingest_tags.yaml

      - name: Notify on failure
        uses: slackapi/slack-github-action@v2.1.0
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":warning: Unable to ingest ownership types metadata on ${{inputs.ENVIRONMENT}} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }