name: Ingest metadata to dev

on:
  # schedule:
  #   - cron: "0 9,14 * * *" # 9am, 2pm UTC
  workflow_dispatch:

jobs:
  ingest-cadet-dev:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: dev
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
