name: "Ingest metadata from ownership types public api"

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Environment to use for secrets"
        required: true
        type: string
    secrets:
      DATAHUB_GMS_TOKEN:
        description: "API Key for datahub GMS"
        required: true
      SLACK_ALERT_WEBHOOK:
        description: "Webhook for posting alerts to the team"
        required: true

jobs:
  datahub-ingest-ownership-types:
    environment: ${{ inputs.ENVIRONMENT }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - run: echo "ENVIRONMENT=${{inputs.ENVIRONMENT}}; URL=${{vars.DATAHUB_GMS_URL}}"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: cache poetry install
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-1.7.1-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction

      - name: ownership types ingestion
        env:
          DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
          DATAHUB_GMS_URL: ${{ vars.DATAHUB_GMS_URL }}
          DATAHUB_TELEMETRY_ENABLED: false
        run: time poetry run datahub ingest -c ingestion/create_custom_ownership_types.yaml

      - name: Notify on failure
        uses: slackapi/slack-github-action@v1.27.0
        if: failure()
        with:
          channel-id: "C071VNHPUHZ"
          payload: |
            {
                "text": ":warning: Unable to ingest ownership types metadata on ${{inputs.ENVIRONMENT}}!",
                "blocks": [
                {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action run result: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                }
                ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ALERT_WEBHOOK }}
