name: Ingest metadata to dev

on:
  # schedule:
  #   - cron: "0 9,14 * * *" # 9am, 2pm UTC
  workflow_dispatch:
  pull_request:

jobs:
  # ingest-ownership-types-dev:
  #   uses: ./.github/workflows/ingest-ownership-types.yml
  #   with:
  #     ENVIRONMENT: dev
  #   secrets:
  #     DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
  #     SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  # ingest-cadet-dev:
  #   uses: ./.github/workflows/ingest-cadet-metadata.yml
  #   with:
  #     ECR_REGION: eu-west-1
  #     ENVIRONMENT: dev
  #   secrets:
  #     DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
  #     CADET_METADATA_ROLE_TO_ASSUME: ${{ secrets.CADET_METADATA_ROLE_TO_ASSUME }}
  #     SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  # ingest-justice-data-dev:
  #   uses: ./.github/workflows/ingest-justice-data.yml
  #   with:
  #     ECR_REGION: eu-west-1
  #     ENVIRONMENT: dev
  #   secrets:
  #     DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
  #     SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
  ingest-glue-data-dev:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ENVIRONMENT: dev
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      SOP_TECHNICAL_CONTACT: ${{ secrets.SOP_TECHNICAL_CONTACT }}
      CONTRACTS_TECHNICAL_CONTACT: ${{ secrets.CONTRACTS_TECHNICAL_CONTACT }}
      COURTS_CRIMINAL_TECHNICAL_CONTACT: ${{ secrets.COURTS_CRIMINAL_TECHNICAL_CONTACT }}
      COURTS_FAMILY_TECHNICAL_CONTACT: ${{ secrets.COURTS_FAMILY_TECHNICAL_CONTACT }}
      JUST_LINK_TECHNICAL_CONTACT: ${{ secrets.JUST_LINK_TECHNICAL_CONTACT }}
  # ingest-moj-publications-dev:
  #   uses: ./.github/workflows/ingest-moj-publications.yml
  #   with:
  #     ENVIRONMENT: dev
  #   secrets:
  #     DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
  #     SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
