name: Ingest metadata to dev

on:
  schedule:
    - cron: "0 9,14 * * *" # 9am, 2pm UTC
  workflow_dispatch:

jobs:
  ingest-cadet-dev:
    uses: ./.github/workflows/ingest-cadet-metadata.yml
    with:
      env: dev
