name: Run Python Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "scripts/**.py"
      - "tests/**.py"
  push:
    branches:
      - main
    paths:
      - "scripts/**.py"
      - "tests/**.py"
      
jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r requirements-dev.txt
        

      - name: run unit tests
        id: python-tests
        run: pytest tests/
