name: Run Python Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "scripts/**.py"
      - "tests/**.py"
  push:
    paths:
      - "scripts/**.py"
      - "tests/**.py"
      
jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install semantic-version pytest

      - name: run unit tests
        id: python-tests
        run: pytest tests/
