name: Run Python Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.17"
      
      - name: Install Project Dependencies
        run: uv sync --locked

      - name: run pytest
        id: pytest
        run: uv run pytest
