name: Ingest glue metadata to dev

on:
  pull_request:

jobs:
  ingest-glue-data-dev:
    uses: ./.github/workflows/ingest-glue-data.yml
    with:
      ECR_REGION: eu-west-1
      ENVIRONMENT: dev
    secrets:
      DATAHUB_GMS_TOKEN: ${{ secrets.DATAHUB_GMS_TOKEN }}
      GLUE_ROLE_TO_ASSUME: ${{ secrets.GLUE_ROLE_TO_ASSUME }}
      SLACK_ALERT_WEBHOOK: ${{ secrets.SLACK_ALERT_WEBHOOK }}
